### ISSUE TITLE
Instance/Network/etc state changes use wrong class attribute

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#975] opened 2021-09-14 05:45 UTC
A lot of state changes use the `dbo.STATE_` attrribute when they should use the state attribute of their class.

There is no operational difference since they are all strings, but it's poor OOP anticipating the inheritance of the object. The user of an OOP object should only use what's in the class and not assume the source of the class inherited objects.

There is added benefit when surfing the code looking at state assignments. The correct class will make finding state changes easier.

Enforcement of this rule is also an issue to be considered.

**Comment by mikalstill** [comment] 2021-10-31 05:47
Duplicate of #974.

**Closed by mikalstill** 2021-10-31 05:47 UTC
